In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
import numpy as np

housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target, random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, random_state=42)

mlp_reg = MLPRegressor(hidden_layer_sizes=[50, 50, 50], random_state=42)
pipeline = make_pipeline(StandardScaler(), mlp_reg)
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_valid)
mse = mean_squared_error(y_valid, y_pred)
rmse = np.sqrt(mse)
print(rmse)

0.5053326657968684


In [ ]:
from sklearn.datasets import load_iris
from sklearn.metrics import log_loss
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
import numpy as np

iris = load_iris()
X_train_full, X_test, y_train_full, y_test = train_test_split(iris.data, iris.target, random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, random_state=42)

mlp_class = MLPClassifier(hidden_layer_sizes=[10], max_iter=500, learning_rate_init=0.01, random_state=42)
pipeline = make_pipeline(StandardScaler(), mlp_class)
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict_proba(X_valid)
loss = log_loss(y_valid, y_pred)
print(loss)

y_pred_class = pipeline.predict_proba(X_valid)
rounded_proba = np.round(y_pred_class, 3)
print("Predicted classes:", y_pred_class)
for true, pred in zip(y_valid, rounded_proba):
    print(f"실제: {true}, 예측: {pred}")

0.04213919924711888
Predicted classes: [[9.99486216e-01 4.39977920e-04 7.38055847e-05]
 [1.65061129e-04 5.79244991e-01 4.20589948e-01]
 [7.24715994e-04 9.86420740e-01 1.28545442e-02]
 [9.98724086e-01 1.26773832e-03 8.17530163e-06]
 [4.64288561e-06 7.32611434e-03 9.92669243e-01]
 [7.33009704e-07 2.30629036e-04 9.99768638e-01]
 [1.48936393e-03 9.95199184e-01 3.31145188e-03]
 [7.99608341e-07 4.31527683e-04 9.99567673e-01]
 [5.89446216e-04 9.96949151e-01 2.46140243e-03]
 [9.99216909e-01 7.78970120e-04 4.12131959e-06]
 [2.38560675e-04 2.60722776e-01 7.39038663e-01]
 [8.16849882e-05 7.75658527e-02 9.22352462e-01]
 [1.67437660e-06 1.99358816e-03 9.98004737e-01]
 [5.26838224e-04 9.72440062e-01 2.70331002e-02]
 [9.99809158e-01 1.76673519e-04 1.41688654e-05]
 [9.99185619e-01 8.06929684e-04 7.45147967e-06]
 [4.70370925e-07 3.35753626e-04 9.99663776e-01]
 [1.59634099e-03 9.98285181e-01 1.18477822e-04]
 [6.34259574e-04 9.98135036e-01 1.23070486e-03]
 [1.21496357e-02 9.86668424e-01 1.18193983e-03]
 

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
iris = load_iris()
X_train_full, X_test, y_train_full, y_test = train_test_split(iris.data, iris.target, random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, random_state=42)

log_reg = LogisticRegression(max_iter=500, random_state=42)
pipeline = make_pipeline(StandardScaler(), log_reg)
pipeline.fit(X_train, y_train)

# 확률값 반환 (아이리스 데이터셋의 경우 ex. [0.    0.579 0.421])
y_pred_proba = pipeline.predict_proba(X_valid)

# 클래스 분류 값 반환 (아이리스 데이터셋의 경우 0, 1, 2중 하나)
y_pred = pipeline.predict(X_valid)
print(y_pred_proba)
print(y_pred)

[[9.77715582e-01 2.22818012e-02 2.61674328e-06]
 [1.95922457e-03 5.21756907e-01 4.76283868e-01]
 [8.82121555e-03 6.76917683e-01 3.14261102e-01]
 [9.38184775e-01 6.18100226e-02 5.20207012e-06]
 [3.93458451e-04 1.64688244e-01 8.34918297e-01]
 [6.82490101e-05 1.80247525e-02 9.81906998e-01]
 [3.66946834e-02 8.39487723e-01 1.23817594e-01]
 [3.65221600e-05 1.75015857e-02 9.82461892e-01]
 [1.32079851e-02 7.91077773e-01 1.95714242e-01]
 [9.56605739e-01 4.33918433e-02 2.41768347e-06]
 [2.64623446e-03 3.60464665e-01 6.36889100e-01]
 [1.92425882e-03 4.41085353e-01 5.56990388e-01]
 [1.67808227e-04 8.51208388e-02 9.14711353e-01]
 [5.07181077e-03 6.18844259e-01 3.76083930e-01]
 [9.82953590e-01 1.70455678e-02 8.41905205e-07]
 [9.60498762e-01 3.94988201e-02 2.41803170e-06]
 [7.90405490e-05 4.09275403e-02 9.58993419e-01]
 [6.81470477e-02 9.08669924e-01 2.31830278e-02]
 [1.78676530e-02 8.44735962e-01 1.37396385e-01]
 [1.41388534e-01 8.41260804e-01 1.73506616e-02]
 [9.58672724e-03 9.27137160e-01 6.327611

In [ ]:
import sklearn
print(sklearn.__version__)
print(mean_squared_error)